import type { Metadata } from "next";
import "./globals.css";
import { Readex_Pro } from "next/font/google";
import Header from "@/components/Header";
import { Languages } from "@/constants/enums";
import Footer from "@/components/Footer";
import Background from "@/components/ui/background";

const readex = Readex_Pro({
  subsets: ["latin", "arabic"],
  variable: "--font-geist-sans",
  weight: ["400", "500", "700"],
  preload: true,
});
export const metadata: Metadata = {
  title: "Visionaries",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
    apple: "/images/logo.png",
    shortcut: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={Languages.EN} data-theme="dark">
      <head>
        <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-N8G6HV5Q');</script>
<!-- End Google Tag Manager -->
      </head>
      <body className={`${readex.className}`}>
        <Background />
        <Header />
        {children}
        <Footer />
        <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N8G6HV5Q"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
      </body>
    </html>
  );
}
