import type { Metadata } from "next";
import "./globals.css";
import { Readex_Pro } from "next/font/google";
import Header from "@/components/Header";
import { Languages } from "@/constants/enums";
import Footer from "@/components/Footer";
import Background from "@/components/ui/background";

const readex = Readex_Pro({
  subsets: ["latin", "arabic"],
  variable: "--font-geist-sans",
  weight: ["400", "500", "700"],
  preload: true,
});
export const metadata: Metadata = {
  title: "Visionaries",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
    apple: "/images/logo.png",
    shortcut: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={Languages.EN} data-theme="dark">
      <body className={`${readex.className}`}>
        <Background />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
